name: Testing stuff

on:
  - workflow_dispatch
  
jobs:
  test1:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
      - name: Run until stopped
        run:
          sleep 600000000
